### ISSUE TITLE
aggregate_result.py is missing from the repository

### ISSUE THREAD

**Issue by koreyou** [swallow-llm/swallow-evaluation#1]
Some of the scripts use a script called `aggregate_result.py` (e.g., [`scripts/evaluate_ja_llmjp.sh`](https://github.com/swallow-llm/swallow-evaluation/blob/13e034d83b33fa629aff9b968f019c29bc8a13f8/scripts/evaluate_ja_llmjp.sh#L42C1-L42C60)), but it is currently missing in the main branch of the repository.
It seems it was deleted in [a recent commit](https://github.com/swallow-llm/swallow-evaluation/commit/5a441ccac4b42fa517c50489fee9663a2330b4c7#diff-3bead9e0815df0ffdce50e45778c188321053382b8f6b90360e00051a65fb687), possibly by accident.

I would recommend maintainers to put it back to `main` unless it was intensional.

**Comment by stjohn2007** [comment]
@koreyou 
Thank you for letting us know the script needs to be included.
We have now restored `aggregate_result.py` to the main branch and added an explanation to the `README.md` file.

If you have any more problems, please feel free to reopen this issue and ask us.

**Comment by koreyou** [comment]
Very much appreciated!
